name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Emscripten 3.0.0
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install 3.0.0
          ./emsdk activate 3.0.0
          source ./emsdk_env.sh
        shell: bash

      - name: Build the project
        run: |
          mkdir build
          cd build
          emcmake cmake -G Ninja ..
          cmake --build .
        shell: bash

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true